import numpy as np
import matplotlib.pyplot as plt
from Boat3DOF import Boat3DOF


def main():
    # Parameters
    params = {
        "m": 70.0,  # Mass of the vessel [kg]
        "Iz": 10.0,  # Yaw moment of inertia about vertical axis [kg·m²]
        "Xu": 5.0,  # Linear surge damping coefficient (viscous drag)
        "Xuu": 1.0,  # Quadratic surge damping coefficient (form drag)
        "Yv": 40.0,  # Linear sway damping (lateral hydrodynamic resistance)
        "Yr": 5.0,  # Cross-coupling damping from yaw rate to sway force
        "Nv": 5.0,  # Yaw moment generated by sway velocity
        "Nr": 40.0,  # Yaw damping (rotational hydrodynamic resistance)
        "l": 0.5,  # Half-distance between left and right thrusters [m]
    }

    boat = Boat3DOF(params)

    dt = 0.05
    t_end = 60.0
    steps = int(t_end / dt)

    # Thrust schedule
    T_straight = (20.0, 20.0)  # 0–20s
    T_turn = (15.0, 25.0)  # 20–60s

    # Storage arrays
    ts = np.zeros(steps + 1)
    xs = np.zeros(steps + 1)
    ys = np.zeros(steps + 1)
    psis = np.zeros(steps + 1)
    us = np.zeros(steps + 1)
    vs = np.zeros(steps + 1)
    rs = np.zeros(steps + 1)

    # Simulation loop
    for k in range(steps + 1):
        t = k * dt

        if t < 20.0:
            T_L, T_R = T_straight
        else:
            T_L, T_R = T_turn

        if k > 0:
            boat.step(T_L, T_R, dt)

        ts[k] = t
        x, y, psi, u, v, r = boat.state
        xs[k] = x
        ys[k] = y
        psis[k] = psi
        us[k] = u
        vs[k] = v
        rs[k] = r

    # Plotting
    # 1) Trajectory
    plt.figure()
    plt.plot(xs, ys)
    plt.xlabel("x [m]")
    plt.ylabel("y [m]")
    plt.title("Boat Trajectory")
    plt.axis("equal")
    plt.grid(True)

    # 2) Surge speed
    plt.figure()
    plt.plot(ts, us)
    plt.xlabel("time [s]")
    plt.title("Surge Speed u(t)")
    plt.grid(True)

    # 3) Heading
    plt.figure()
    plt.plot(ts, psis)
    plt.xlabel("time [s]")
    plt.ylabel("psi [rad]")
    plt.title("Heading psi(t)")
    plt.grid(True)

    # 4) Yaw rate
    plt.figure()
    plt.plot(ts, rs)
    plt.xlabel("time [s]")
    plt.ylabel("r [rad/s]")
    plt.title("Yaw rate r(t)")
    plt.grid(True)

    plt.show()


if __name__ == "__main__":
    main()
