std_msgs/Header header
string model
bool is_6dof
float32 dt
float32 thrust_cmd
float32 delta_cmd
float32 thrust
float32 delta

float32 r_g_x
float32 r_g_y
float32 r_g_z
float32 r_b_x
float32 r_b_y
float32 r_b_z
float32 weight_n
float32 buoyancy_n

float32 x
float32 y
float32 z
float32 qw
float32 qx
float32 qy
float32 qz
float32 roll
float32 pitch
float32 yaw

float32 u
float32 v
float32 w
float32 p
float32 q
float32 r

float32 x_dot
float32 y_dot
float32 z_dot

float32 u_dot
float32 v_dot
float32 w_dot
float32 p_dot
float32 q_dot
float32 r_dot

float32 tau_x
float32 tau_y
float32 tau_z
float32 tau_k
float32 tau_m
float32 tau_n

float32 coriolis_rb_x
float32 coriolis_rb_y
float32 coriolis_rb_z
float32 coriolis_rb_k
float32 coriolis_rb_m
float32 coriolis_rb_n

float32 coriolis_a_x
float32 coriolis_a_y
float32 coriolis_a_z
float32 coriolis_a_k
float32 coriolis_a_m
float32 coriolis_a_n

float32 damping_x
float32 damping_y
float32 damping_z
float32 damping_k
float32 damping_m
float32 damping_n

float32 restoring_x
float32 restoring_y
float32 restoring_z
float32 restoring_k
float32 restoring_m
float32 restoring_n
