#!/usr/bin/env python3

import math
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
UTILS_PATH = os.path.join(ROOT, "src", "na_utils")
if UTILS_PATH not in sys.path:
    sys.path.insert(0, UTILS_PATH)

from na_utils.bspline import BSplinePath  # noqa: E402

FIG_DIR = os.path.join(os.path.dirname(__file__), "..", "figures")


def ensure_dir() -> None:
    os.makedirs(FIG_DIR, exist_ok=True)


def downsample(points, max_points=140):
    if len(points) <= max_points:
        return list(points)
    step = int(math.ceil(len(points) / max_points))
    sampled = list(points[::step])
    if sampled[-1] != points[-1]:
        sampled.append(points[-1])
    return sampled


def fmt_point(point) -> str:
    return f"({point[0]:.3f},{point[1]:.3f})"


def fmt_coords(points) -> str:
    return " ".join(fmt_point(point) for point in points)


def write_tikz(filename: str, lines) -> None:
    path = os.path.join(FIG_DIR, filename)
    with open(path, "w", encoding="ascii") as handle:
        handle.write("% Auto-generated by latex/scripts/generate_figures.py\n")
        for line in lines:
            handle.write(line)
            if not line.endswith("\n"):
                handle.write("\n")


def los_example() -> None:
    control = [
        (0.0, 0.0),
        (4.0, 1.0),
        (6.0, 4.0),
        (4.0, 7.0),
        (0.0, 6.0),
        (-2.0, 3.0),
    ]
    path = BSplinePath(control, start_u=0.0, samples=400, closed=True)

    t0 = path.length * 0.2
    sample = path.sample_at_t(t0)
    offset = 1.0
    boat = (
        sample.point[0] + offset * sample.normal[0],
        sample.point[1] + offset * sample.normal[1],
    )
    proj = path.project(boat[0], boat[1])
    if proj is None:
        raise RuntimeError("LOS example projection failed")

    lookahead = 3.0
    target_t = path.advance_t(proj.t, lookahead)
    target = path.sample_at_t(target_t).point

    tangent_len = 0.8
    tangent_end = (
        proj.point[0] + proj.tangent[0] * tangent_len,
        proj.point[1] + proj.tangent[1] * tangent_len,
    )

    path_points = downsample(path.points, max_points=160)
    coords = fmt_coords(path_points)

    lines = [
        "\\begin{tikzpicture}[>=Latex,scale=1.0]",
        f"  \\draw[thick] plot [smooth cycle] coordinates {{ {coords} }};",
        f"  \\coordinate (boat) at {fmt_point(boat)};",
        f"  \\coordinate (proj) at {fmt_point(proj.point)};",
        f"  \\coordinate (target) at {fmt_point(target)};",
        f"  \\coordinate (tan) at {fmt_point(tangent_end)};",
        "  \\fill (boat) circle (1.4pt);",
        "  \\node[anchor=west] at (boat) {boat};",
        "  \\fill (proj) circle (1.4pt);",
        "  \\node[anchor=south east] at (proj) {projection};",
        "  \\fill (target) circle (1.4pt);",
        "  \\node[anchor=south] at (target) {lookahead};",
        "  \\draw[->,red] (proj) -- (boat) node[midway,right] {cte};",
        "  \\draw[->,blue] (proj) -- (target) node[midway,above] {lookahead};",
        "  \\draw[->,gray] (proj) -- (tan) node[above] {tangent};",
        "\\end{tikzpicture}",
    ]
    write_tikz("los_example.tikz", lines)


def open_end_example() -> None:
    control = [
        (-4.0, 0.0),
        (-2.5, 1.2),
        (-0.5, 1.8),
        (1.5, 1.2),
        (3.5, 0.0),
        (5.0, -0.5),
    ]
    path = BSplinePath(control, start_u=0.0, samples=300, closed=False)

    t0 = path.length * 0.85
    sample = path.sample_at_t(t0)
    offset = 0.8
    boat = (
        sample.point[0] + offset * sample.normal[0],
        sample.point[1] + offset * sample.normal[1],
    )
    proj = path.project(boat[0], boat[1])
    if proj is None:
        raise RuntimeError("Open-end example projection failed")

    lookahead = 2.5
    target_t = path.advance_t(proj.t, lookahead)
    target = path.sample_at_t(target_t).point

    end_sample = path.sample_at_t(path.t_end)
    end_point = end_sample.point
    end_tangent = end_sample.tangent
    beyond = (
        end_point[0] + end_tangent[0] * 1.2,
        end_point[1] + end_tangent[1] * 1.2,
    )

    path_points = downsample(path.points, max_points=120)
    coords = fmt_coords(path_points)

    lines = [
        "\\begin{tikzpicture}[>=Latex,scale=1.0]",
        f"  \\draw[thick] plot [smooth] coordinates {{ {coords} }};",
        f"  \\coordinate (boat) at {fmt_point(boat)};",
        f"  \\coordinate (proj) at {fmt_point(proj.point)};",
        f"  \\coordinate (target) at {fmt_point(target)};",
        f"  \\coordinate (endpt) at {fmt_point(end_point)};",
        f"  \\coordinate (beyond) at {fmt_point(beyond)};",
        "  \\fill (boat) circle (1.4pt);",
        "  \\node[anchor=west] at (boat) {boat};",
        "  \\fill (proj) circle (1.4pt);",
        "  \\node[anchor=south] at (proj) {projection};",
        "  \\fill (target) circle (1.4pt);",
        "  \\node[anchor=south] at (target) {lookahead};",
        "  \\fill (endpt) circle (1.2pt);",
        "  \\node[anchor=south] at (endpt) {end};",
        "  \\draw[->,red] (proj) -- (boat) node[midway,right] {cte};",
        "  \\draw[->,blue] (proj) -- (target) node[midway,above] {lookahead clamps};",
        "  \\draw[dashed] (endpt) -- (beyond) node[anchor=west] {beyond end};",
        "\\end{tikzpicture}",
    ]
    write_tikz("open_end.tikz", lines)


def sampling_density_example() -> None:
    control = [
        (-4.0, 0.0),
        (-3.0, 2.0),
        (-1.0, 3.0),
        (1.0, 3.0),
        (3.0, 2.0),
        (4.0, 0.0),
        (3.0, -2.0),
        (1.0, -3.0),
        (-1.0, -3.0),
        (-3.0, -2.0),
    ]
    fine = BSplinePath(control, start_u=0.0, samples=400, closed=True)
    coarse = BSplinePath(control, start_u=0.0, samples=30, closed=True)

    fine_coords = fmt_coords(downsample(fine.points, max_points=200))
    coarse_coords = fmt_coords(coarse.points)
    coarse_points = ", ".join(fmt_point(point) for point in coarse.points)

    xs = [point[0] for point in fine.points]
    ys = [point[1] for point in fine.points]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    legend_x = max_x + 0.4
    legend_y = max_y - 0.4
    legend_gap = 0.5

    lines = [
        "\\begin{tikzpicture}[>=Latex,scale=0.95]",
        f"  \\draw[thick,blue] plot [smooth cycle] coordinates {{ {fine_coords} }};",
        f"  \\draw[orange,dashed] plot [smooth cycle] coordinates {{ {coarse_coords} }};",
        "  \\foreach \\p in {" + coarse_points + "} { \\fill[orange] \\p circle (0.7pt); }",
        f"  \\draw[blue,thick] ({legend_x - 1.0:.3f},{legend_y:.3f}) -- ({legend_x - 0.2:.3f},{legend_y:.3f});",
        f"  \\node[blue,anchor=west] at ({legend_x:.3f},{legend_y:.3f}) {{fine path}};",
        f"  \\draw[orange,dashed] ({legend_x - 1.0:.3f},{legend_y - legend_gap:.3f}) -- ({legend_x - 0.2:.3f},{legend_y - legend_gap:.3f});",
        f"  \\fill[orange] ({legend_x - 0.6:.3f},{legend_y - legend_gap:.3f}) circle (0.7pt);",
        f"  \\node[orange,anchor=west] at ({legend_x:.3f},{legend_y - legend_gap:.3f}) {{coarse samples}};",
        "\\end{tikzpicture}",
    ]
    write_tikz("sampling_density.tikz", lines)


def main() -> None:
    ensure_dir()
    los_example()
    open_end_example()
    sampling_density_example()


if __name__ == "__main__":
    main()
