#!/usr/bin/env python3

import math
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
UTILS_PATH = os.path.join(ROOT, "src", "na_utils")
if UTILS_PATH not in sys.path:
    sys.path.insert(0, UTILS_PATH)

from na_utils.bspline import BSplinePath  # noqa: E402

FIG_DIR = os.path.join(os.path.dirname(__file__), "..", "figures")


def ensure_dir() -> None:
    os.makedirs(FIG_DIR, exist_ok=True)


def downsample(points, max_points=140):
    if len(points) <= max_points:
        return list(points)
    step = int(math.ceil(len(points) / max_points))
    sampled = list(points[::step])
    if sampled[-1] != points[-1]:
        sampled.append(points[-1])
    return sampled


def fmt_point(point) -> str:
    return f"({point[0]:.3f},{point[1]:.3f})"


def fmt_coords(points) -> str:
    return " ".join(fmt_point(point) for point in points)


def bounds(points):
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    return min(xs), max(xs), min(ys), max(ys)


def write_tikz(filename: str, lines) -> None:
    path = os.path.join(FIG_DIR, filename)
    with open(path, "w", encoding="ascii") as handle:
        handle.write("% Auto-generated by latex/scripts/generate_figures.py\n")
        for line in lines:
            handle.write(line)
            if not line.endswith("\n"):
                handle.write("\n")


def los_example() -> None:
    control = [
        (0.0, 0.0),
        (4.0, 1.0),
        (6.0, 4.0),
        (4.0, 7.0),
        (0.0, 6.0),
        (-2.0, 3.0),
    ]
    path = BSplinePath(control, start_u=0.0, samples=400, closed=True)

    t0 = path.length * 0.2
    sample = path.sample_at_t(t0)
    offset = 1.0
    boat = (
        sample.point[0] + offset * sample.normal[0],
        sample.point[1] + offset * sample.normal[1],
    )
    proj = path.project(boat[0], boat[1])
    if proj is None:
        raise RuntimeError("LOS example projection failed")

    lookahead = 3.0
    target_t = path.advance_t(proj.t, lookahead)
    target = path.sample_at_t(target_t).point

    tangent_len = 0.8
    tangent_end = (
        proj.point[0] + proj.tangent[0] * tangent_len,
        proj.point[1] + proj.tangent[1] * tangent_len,
    )

    path_points = downsample(path.points, max_points=160)
    coords = fmt_coords(path_points)
    min_x, max_x, min_y, max_y = bounds(path_points)
    legend_x = max_x + 1.0
    legend_y = max_y - 0.2
    legend_gap = 0.45
    legend_label_x = legend_x + 0.25

    lines = [
        "\\begin{tikzpicture}[>=Latex,scale=1.0,every node/.style={font=\\scriptsize}]",
        "  \\tikzset{",
        "    path/.style={thick,black!70},",
        "    cte/.style={red!70!black,thick,->},",
        "    look/.style={blue!70!black,thick,->},",
        "    tan/.style={gray!70,->},",
        "    boat/.style={circle,fill=black,inner sep=1.2pt},",
        "    proj/.style={circle,draw=red!70!black,fill=white,inner sep=1.2pt},",
        "    lookahead/.style={regular polygon,regular polygon sides=3,draw=blue!70!black,fill=blue!20,minimum size=5pt,inner sep=0pt,rotate=90}",
        "  }",
        f"  \\draw[path] plot [smooth cycle] coordinates {{ {coords} }};",
        f"  \\coordinate (boat) at {fmt_point(boat)};",
        f"  \\coordinate (proj) at {fmt_point(proj.point)};",
        f"  \\coordinate (target) at {fmt_point(target)};",
        f"  \\coordinate (tan) at {fmt_point(tangent_end)};",
        "  \\node[boat] at (boat) {};",
        "  \\node[proj] at (proj) {};",
        "  \\node[lookahead] at (target) {};",
        "  \\draw[cte] (proj) -- (boat) node[midway,right] {cte};",
        "  \\draw[look] (proj) -- (target) node[midway,above] {L};",
        "  \\draw[tan] (proj) -- (tan) node[above] {t};",
        f"  \\node[boat] at ({legend_x:.3f},{legend_y:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y:.3f}) {{B boat}};",
        f"  \\node[proj] at ({legend_x:.3f},{legend_y - legend_gap:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - legend_gap:.3f}) {{P proj}};",
        f"  \\node[lookahead] at ({legend_x:.3f},{legend_y - 2.0 * legend_gap:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - 2.0 * legend_gap:.3f}) {{L look}};",
        "\\end{tikzpicture}",
    ]
    write_tikz("los_example.tikz", lines)


def open_end_example() -> None:
    control = [
        (-4.0, 0.0),
        (-2.5, 1.2),
        (-0.5, 1.8),
        (1.5, 1.2),
        (3.5, 0.0),
        (5.0, -0.5),
    ]
    path = BSplinePath(control, start_u=0.0, samples=300, closed=False)

    t0 = path.length * 0.85
    sample = path.sample_at_t(t0)
    offset = 0.8
    boat = (
        sample.point[0] + offset * sample.normal[0],
        sample.point[1] + offset * sample.normal[1],
    )
    proj = path.project(boat[0], boat[1])
    if proj is None:
        raise RuntimeError("Open-end example projection failed")

    lookahead = 2.5
    target_t = path.advance_t(proj.t, lookahead)
    target = path.sample_at_t(target_t).point

    end_sample = path.sample_at_t(path.t_end)
    end_point = end_sample.point
    end_tangent = end_sample.tangent
    beyond = (
        end_point[0] + end_tangent[0] * 1.2,
        end_point[1] + end_tangent[1] * 1.2,
    )

    path_points = downsample(path.points, max_points=120)
    coords = fmt_coords(path_points)
    min_x, max_x, min_y, max_y = bounds(path_points)
    legend_x = max_x + 0.8
    legend_y = max_y - 0.1
    legend_gap = 0.45
    legend_label_x = legend_x + 0.25
    beyond_label = (beyond[0] + 0.1, beyond[1] + 0.1)

    lines = [
        "\\begin{tikzpicture}[>=Latex,scale=1.0,every node/.style={font=\\scriptsize}]",
        "  \\tikzset{",
        "    path/.style={thick,black!70},",
        "    cte/.style={red!70!black,thick,->},",
        "    look/.style={blue!70!black,thick,->},",
        "    boat/.style={circle,fill=black,inner sep=1.2pt},",
        "    proj/.style={circle,draw=red!70!black,fill=white,inner sep=1.2pt},",
        "    lookahead/.style={regular polygon,regular polygon sides=3,draw=blue!70!black,fill=blue!20,minimum size=5pt,inner sep=0pt,rotate=90},",
        "    endpt/.style={rectangle,draw=green!60!black,fill=white,minimum size=4pt,inner sep=0pt}",
        "  }",
        f"  \\draw[path] plot [smooth] coordinates {{ {coords} }};",
        f"  \\coordinate (boat) at {fmt_point(boat)};",
        f"  \\coordinate (proj) at {fmt_point(proj.point)};",
        f"  \\coordinate (target) at {fmt_point(target)};",
        f"  \\coordinate (endpt) at {fmt_point(end_point)};",
        f"  \\coordinate (beyond) at {fmt_point(beyond)};",
        "  \\node[boat] at (boat) {};",
        "  \\node[proj] at (proj) {};",
        "  \\node[lookahead] at (target) {};",
        "  \\node[endpt] at (endpt) {};",
        "  \\draw[cte] (proj) -- (boat) node[midway,right] {cte};",
        "  \\draw[look] (proj) -- (target) node[midway,above] {L};",
        "  \\draw[dashed,gray] (endpt) -- (beyond);",
        f"  \\node[anchor=west] at {fmt_point(beyond_label)} {{beyond}};",
        f"  \\node[boat] at ({legend_x:.3f},{legend_y:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y:.3f}) {{B boat}};",
        f"  \\node[proj] at ({legend_x:.3f},{legend_y - legend_gap:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - legend_gap:.3f}) {{P proj}};",
        f"  \\node[lookahead] at ({legend_x:.3f},{legend_y - 2.0 * legend_gap:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - 2.0 * legend_gap:.3f}) {{L look}};",
        f"  \\node[endpt] at ({legend_x:.3f},{legend_y - 3.0 * legend_gap:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - 3.0 * legend_gap:.3f}) {{E end}};",
        "\\end{tikzpicture}",
    ]
    write_tikz("open_end.tikz", lines)


def sampling_density_example() -> None:
    control = [
        (-4.0, 0.0),
        (-3.0, 2.0),
        (-1.0, 3.0),
        (1.0, 3.0),
        (3.0, 2.0),
        (4.0, 0.0),
        (3.0, -2.0),
        (1.0, -3.0),
        (-1.0, -3.0),
        (-3.0, -2.0),
    ]
    fine = BSplinePath(control, start_u=0.0, samples=400, closed=True)
    coarse = BSplinePath(control, start_u=0.0, samples=30, closed=True)

    fine_coords = fmt_coords(downsample(fine.points, max_points=200))
    coarse_coords = fmt_coords(coarse.points)
    coarse_points = ", ".join(fmt_point(point) for point in coarse.points)

    min_x, max_x, min_y, max_y = bounds(fine.points)
    legend_x = max_x + 0.6
    legend_y = max_y - 0.2
    legend_gap = 0.45
    legend_line_x0 = legend_x - 0.9
    legend_line_x1 = legend_x - 0.3
    legend_label_x = legend_x + 0.05
    legend_point_x = legend_x - 0.6

    lines = [
        "\\begin{tikzpicture}[>=Latex,scale=0.95,every node/.style={font=\\scriptsize}]",
        "  \\tikzset{",
        "    finepath/.style={thick,black!70},",
        "    coarsepath/.style={orange!80!black,dashed},",
        "    coarsept/.style={circle,draw=orange!80!black,fill=orange!40,inner sep=0.6pt}",
        "  }",
        f"  \\draw[finepath] plot [smooth cycle] coordinates {{ {fine_coords} }};",
        f"  \\draw[coarsepath] plot [smooth cycle] coordinates {{ {coarse_coords} }};",
        "  \\foreach \\p in {" + coarse_points + "} { \\node[coarsept] at \\p {}; }",
        f"  \\draw[finepath] ({legend_line_x0:.3f},{legend_y:.3f}) -- ({legend_line_x1:.3f},{legend_y:.3f});",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y:.3f}) {{fine path}};",
        f"  \\draw[coarsepath] ({legend_line_x0:.3f},{legend_y - legend_gap:.3f}) -- ({legend_line_x1:.3f},{legend_y - legend_gap:.3f});",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - legend_gap:.3f}) {{coarse path}};",
        f"  \\node[coarsept] at ({legend_point_x:.3f},{legend_y - 2.0 * legend_gap:.3f}) {{}};",
        f"  \\node[anchor=west] at ({legend_label_x:.3f},{legend_y - 2.0 * legend_gap:.3f}) {{samples}};",
        "\\end{tikzpicture}",
    ]
    write_tikz("sampling_density.tikz", lines)


def main() -> None:
    ensure_dir()
    los_example()
    open_end_example()
    sampling_density_example()


if __name__ == "__main__":
    main()
